// <auto-generated />
using System;
using CookGuide.API.Shared.Persistence.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CookGuide.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("CookGuide.API.Accounts.Domain.Models.Accounts", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("address")
                        .HasColumnType("longtext")
                        .HasColumnName("address");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("email");

                    b.Property<string>("firstName")
                        .HasColumnType("longtext")
                        .HasColumnName("first_name");

                    b.Property<string>("lastName")
                        .HasColumnType("longtext")
                        .HasColumnName("last_name");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("password");

                    b.Property<string>("phone")
                        .HasColumnType("longtext")
                        .HasColumnName("phone");

                    b.Property<string>("profilePicture")
                        .HasColumnType("longtext")
                        .HasColumnName("profile_picture");

                    b.Property<bool?>("userType")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("user_type");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("username");

                    b.HasKey("id")
                        .HasName("pk_accounts");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("CookGuide.API.Ingredients.Domain.Models.Ingredients", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<string>("nutrients")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("nutrients");

                    b.Property<string>("other_names")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("other_names");

                    b.HasKey("id")
                        .HasName("pk_ingredients");

                    b.ToTable("ingredients", (string)null);
                });

            modelBuilder.Entity("CookGuide.API.Recipes.Domain.Models.Recipes", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    b.Property<int>("accountId")
                        .HasColumnType("int")
                        .HasColumnName("account_id");

                    b.Property<string>("category")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("category");

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("description");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("name");

                    b.Property<int?>("num_portions")
                        .HasColumnType("int")
                        .HasColumnName("num_portions");

                    b.Property<string>("photoUrl")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("photo_url");

                    b.Property<int?>("preparationTime")
                        .HasColumnType("int")
                        .HasColumnName("preparation_time");

                    b.Property<float?>("serving_price")
                        .HasColumnType("float")
                        .HasColumnName("serving_price");

                    b.HasKey("id")
                        .HasName("pk_recipes");

                    b.HasIndex("accountId")
                        .HasDatabaseName("ix_recipes_account_id");

                    b.ToTable("recipes", (string)null);
                });

            modelBuilder.Entity("CookGuide.API.Recipes.Domain.Models.RecipesIngredients", b =>
                {
                    b.Property<int>("RecipeId")
                        .HasColumnType("int")
                        .HasColumnName("recipe_id");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int")
                        .HasColumnName("ingredient_id");

                    b.Property<string>("Measurement")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("measurement");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("quantity");

                    b.HasKey("RecipeId", "IngredientId")
                        .HasName("pk_recipes_ingredients");

                    b.HasIndex("IngredientId")
                        .HasDatabaseName("ix_recipes_ingredients_ingredient_id");

                    b.ToTable("recipes_ingredients", (string)null);
                });

            modelBuilder.Entity("CookGuide.API.Recipes.Domain.Models.Recipes", b =>
                {
                    b.HasOne("CookGuide.API.Accounts.Domain.Models.Accounts", "account")
                        .WithMany("recipes")
                        .HasForeignKey("accountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_accounts_account_id");

                    b.Navigation("account");
                });

            modelBuilder.Entity("CookGuide.API.Recipes.Domain.Models.RecipesIngredients", b =>
                {
                    b.HasOne("CookGuide.API.Ingredients.Domain.Models.Ingredients", "Ingredient")
                        .WithMany("recipes")
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_ingredients_ingredients_ingredient_id");

                    b.HasOne("CookGuide.API.Recipes.Domain.Models.Recipes", "Recipe")
                        .WithMany("ingredients")
                        .HasForeignKey("RecipeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_recipes_ingredients_recipes_recipe_id");

                    b.Navigation("Ingredient");

                    b.Navigation("Recipe");
                });

            modelBuilder.Entity("CookGuide.API.Accounts.Domain.Models.Accounts", b =>
                {
                    b.Navigation("recipes");
                });

            modelBuilder.Entity("CookGuide.API.Ingredients.Domain.Models.Ingredients", b =>
                {
                    b.Navigation("recipes");
                });

            modelBuilder.Entity("CookGuide.API.Recipes.Domain.Models.Recipes", b =>
                {
                    b.Navigation("ingredients");
                });
#pragma warning restore 612, 618
        }
    }
}
